title: 我的博客
email: your-email@example.com
description: >- # 这个符号表示下面的内容是一个多行字符串
  这是我的个人博客，在这里我会分享一些技术文章和个人想法。
baseurl: "" # 子路径，例如 "/blog"
url: "" # 网站的根地址，例如 "http://example.com"
twitter_username: your-twitter-username
github_username:  your-github-username

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# 排除不需要处理的文件
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
